# bNavi Configuration File

config-version: 1
enable-metrics: true
playEffects: true

menu-title: Navigation Points
menu-item-enum: COMPASS

points:
  enabled:
  - centerOfTheWorld
  
  centerOfTheWorld:
    name: Center of the World
    desc: The center of this world!
    world: world
    item: NETHER_STAR
    X: 0
    Z: 0