name: bNavi
main: tk.thapengwin.Navigation
version: 1.1
description: A plugin that helps navigate your players around your world.
author: ThaPengwin
commands:
   navigation:
      description: Navigation admin commands.
      usage: /nav
      aliases: [bnavi, bnavigation, navigation, navigate, nav, where]
      permission: navigation.admin
      permission-message: You don't have permission!
      default: op
permissions:
   navigation.*:
      description: Gives all bNavi features.
      children:
        navigation: true
        navigation.admin: true
   navigation:
      description: Allows the player to use the compass.
      default: true
   navigation.admin:
      description: Allows the player to use admin commands.
      default: op