name: ${name}
version: ${version}
main: ${groupId}.Main
description: Main via compass in Minecraft
author: StashCat

commands:
  navigate:
    aliases: [navigation, nav]
    description: Main command
    permission: navigation
    usage: /navigate <player> OR /navigate <x> (y) <z>
  track:
    aliases: [navigationtrack, navtrack, trackplayer]
    description: Player tracking command
    permission: navigation.track
    usage: /track <player>
  waypoint:
    aliases: [navigationwaypoint, navwaypoint]
    description: Waypoint editing command
    permission: navigation.edit
    usage: /waypoint

permissions:
   navigation:
     description: Allows usage of the /navigate command and navigating via compass
     default: true
   navigation.coordinates:
     description: Allows navigating to specific coordinates
     default: true
   navigation.compass:
     description: Allows using a compass to start navigation
     default: true
   navigation.edit:
     description: Allows editing navigation waypoints
     default: op
   navigation.track:
     description: Allows usage of the /track command, which tracks player location
     default: op
   navigation.chatcoords:
     description: Allows player to start navigation by clicking on coordinates in chat
     default: true
