name: ${name}
version: ${version}
main: ${groupId}.Main
description: Main via compass in Minecraft
author: StashCat

commands:
  navigation:
    description: Navigation plugin management command
    permission: navigation.admin
    usage: /navigation
  navigate:
    aliases: [nav]
    description: Main command
    permission: navigation
    usage: /navigate <waypoint> OR /navigate <x> (y) <z>
  track:
    aliases: [navtrack, trackplayer]
    description: Player tracking command
    permission: navigation.track
    usage: /track <player>
  waypoint:
    aliases: [navwaypoint]
    description: Waypoint editing command
    permission: navigation.edit
    usage: /waypoint

permissions:
  navigation:
    description: Allows usage of the /navigate command and navigating via compass
    default: true
  navigation.coordinates:
    description: Allows navigating to specific coordinates
    default: true
  navigation.compass:
    description: Allows using a compass to start navigation
    default: true
  navigation.edit:
    description: Allows editing navigation waypoints
    default: op
  navigation.track:
    description: Allows usage of the /track command, which tracks player location
    default: op
  navigation.chatcoords:
    description: Allows player to start navigation by clicking on coordinates in chat
    default: true
  navigation.receivecompass:
    description: Allows the player to receive a compass if they do not have one when navigating.
    default: false
  navigation.admin:
    description: Allows the player to manage the plugin.
    default: op
